apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: inventory
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - mountPath: /var/lib/mysql
              subPath: mysql
              name: mysql-data
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-space
      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    DROP SCHEMA IF EXISTS `inventory`;
    CREATE DATABASE IF NOT EXISTS `inventory`;
    USE `inventory`;
    DROP TABLE IF EXISTS `inventory`;
        create table `inventory` (
        `inventory_id` int not null auto_increment,
        `product_id` int not null,
        `quantity` int not null,
        `sold` int not null,
    primary key (`inventory_id`)
        ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
    INSERT INTO `inventory` VALUES (1, 1, 1, 1);
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: kubernetes.io/basic-auth
stringData:
  password: "123456"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  selector:
    app: mysql