apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cart-service
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  strategy: {}
  template:
    metadata:

      labels:
        app: cart-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-cart:5432/cart-service
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: cart-service:latest
          name: cart-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cart-service
  name: cart-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    app: cart-service
status:
  loadBalancer: {}
