kubectl apply -f infrastructure/api-gateway/api-gateway-deployment.yml
kubectl apply -f infrastructure/discovery-server/discovery-server-deployment.yml
kubectl apply -f infrastructure/keycloak/keycloak-deployment.yml
kubectl apply -f infrastructure/keycloak-mysql/keycloak-mysql-deployment.yml
kubectl apply -f infrastructure/mongodb/mongo-deployment.yml
kubectl apply -f infrastructure/postgres-order/postgres-order-deployment.yml
kubectl apply -f infrastructure/postgres-cart/postgres-cart-deployment.yml
kubectl apply -f service/cart-service/cart-service-deployment.yml
kubectl apply -f service/order-service/order-service-deployment.yml
kubectl apply -f service/product-service/product-service-deployment.yml