apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3308
          env:
            - name: MYSQL_DATABASE
              value: hb-customer
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - mountPath: /var/lib/mysql
              subPath: mysql
              name: mysql-data
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-space
      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    DROP SCHEMA IF EXISTS `hb-customer`;
    CREATE DATABASE IF NOT EXISTS `hb-customer`;
    USE `hb-customer`;
    DROP TABLE IF EXISTS `customers`;
        create table `customers` (
        `customer_id` int not null auto_increment,
        `user_name` nvarchar(100) default null,
        `phone_number` nvarchar(100) default null,
    primary key (`customer_id`)
        ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
    INSERT INTO `customers` VALUES (0, 1, 'Abhijeet');
     INSERT INTO `customers` VALUES (0, 1, 'Khanh');
      INSERT INTO `customers` VALUES (0, 1, 'Dung');
       INSERT INTO `customers` VALUES (0, 1, 'Hai');
        INSERT INTO `customers` VALUES (0, 1, 'Duc');
         INSERT INTO `customers` VALUES (0, 1, 'Ngoc');
          INSERT INTO `customers` VALUES (0, 1, 'Ly');
           INSERT INTO `customers` VALUES (0, 1, 'Vy');
            INSERT INTO `customers` VALUES (0, 1, 'Thao');
             INSERT INTO `customers` VALUES (0, 1, 'Mai');
              INSERT INTO `customers` VALUES (0, 1, 'BBB');

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: kubernetes.io/basic-auth
stringData:
  password: "123456"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - name: "3308"
      port: 3308
      targetPort: 3308
  selector:
    app: mysql
