apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/d/data"
