apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer-service
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  strategy: {}
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mysql-customer
            - name: DB_NAME
              value: hb-customer
            - name: DB_USERNAME 
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-customer:3306/hb-customer?enabledTLSProtocols=TLSv1.2&useSSL=false
              #value: jdbc:mysql://localhost:3306/hb-customer?enabledTLSProtocols=TLSv1.2&useSSL=false
          image: customer-service:latest
          envFrom:
            - configMapRef:
                name: mongo-config
          name: customer-service
          ports:
            - containerPort: 9911
          imagePullPolicy: Never
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-service
  name: customer-service
spec:
  ports:
    - name: "90"
      port: 90
      targetPort: 9911
  selector:
    app: customer-service
status:
  loadBalancer: {}
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
    MONGO_HOST: 127.0.0.1
    MONGO_DB: user-db
    MONGO_AUTHEN_DB: admin
    MONGO_USER: khanh
    MONGO_PASSWORD: "123456"
    MONGO_PORT: "27017"


