apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment # name of 'Deployment'
  labels:
    app: mysql
spec: #specific
  replicas: 1
  selector: #select pods with label 'mysql'
    matchLabels:
      app: mysql
  strategy: #strategy to use to replace existing pods with new ones.
    type: Recreate #`"Recreate"` Kill all existing pods before creating new ones.
  template:
    metadata:
      labels:
        app: mysql #pod's label
    spec:
      containers:
        - name: mysql # container's name
          image: mysql:5.7 #docker image from dockerhub or local
          ports:
            - containerPort: 3306 # port which container is running on
          env: #evironment variable
            - name: MYSQL_DATABASE
              value: hb-order
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - mountPath: /var/lib/mysqlmine
              subPath: mysql
              name: mysql-data
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-space
      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap #hold cconfiguration data for port to consume
metadata:
  name: mysql-initdb-config
data: #contain the configuration data
  init.sql: |
    DROP SCHEMA IF EXISTS `hb-order`;
    CREATE DATABASE IF NOT EXISTS `hb-order`;
    USE `hb-order`;
    DROP TABLE IF EXISTS `orders`;
        create table `orders` (
        `order_id` int not null auto_increment,
        `cart_id` int,
        `short_desc` nvarchar(100) default null,
        `is_paid` boolean default null,
        `total_price` double default null,
    primary key (`order_id`)
        ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
    INSERT INTO `orders` VALUES (1, 1, 'Abhijeet', false, 200.00);

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: kubernetes.io/basic-auth
stringData:
  password: "123456"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql #define Service's name
spec:
  ports:
    - name: "3307"
      port: 3307 #Port service is running on
      targetPort: 3306 #port service send request to
  selector:
    app: mysql #must match with pod at Deployment
