apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: hb-order
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
            - mountPath: /var/lib/mysql
              subPath: mysql
              name: mysql-data
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-space
      restartPolicy: Always

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    DROP SCHEMA IF EXISTS `hb-order`;
    CREATE DATABASE IF NOT EXISTS `hb-order`;
    USE `hb-order`;
    DROP TABLE IF EXISTS `orders`;
        create table `orders` (
        `order_id` int not null auto_increment,
        `cart_id` int,
        `short_desc` nvarchar(100) default null,
        `is_paid` boolean default null,
        `total_price` double default null,
    primary key (`order_id`)
        ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
    INSERT INTO `orders` VALUES (1, 1, 'Abhijeet', false, 200.00);

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: kubernetes.io/basic-auth
stringData:
  password: "123456"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  selector:
    app: mysql
