apiVersion: v1
kind: PersistentVolume #PersistentVolume (PV) is a storage resource provisioned by an administrator
metadata:
  name: mysql-data-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/d"
